-- ===== ข้อมูลนำเข้าจากระบบพัสดุเดิม (rtafnc-governance-supplies) =====
-- ล้างข้อมูลตัวอย่าง / ข้อมูลเดิมทั้งหมด (ผู้ใช้ยืนยันแล้ว)
DELETE FROM movements;
DELETE FROM drafts;
DELETE FROM processed_events;
DELETE FROM stock_levels;
DELETE FROM products;
DELETE FROM locations;

INSERT INTO locations (code, name, is_default, active) VALUES ('GOV-WH', 'คลังพัสดุแผนกปกครอง วพอ.', 1, 1);

INSERT INTO products (sku, barcode, name, category, unit, min_qty, note, active) VALUES
('GOV-APP-001', NULL, 'รองเท้าพยาบาล size 35', 'พัสดุปกครอง ๑', 'คู่', 0, 'ภาพ: item_2.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-002', NULL, 'รองเท้าพยาบาล size 36', 'พัสดุปกครอง ๑', 'คู่', 0, 'ภาพ: item_3.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-003', NULL, 'ถุงมือสีขาว', 'พัสดุปกครอง ๑', 'คู่', 0, 'ภาพ: item_4.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-004', NULL, 'หมวกแก๊ปสีขาวรักพ่อ', 'พัสดุปกครอง ๑', 'ใบ', 0, 'ภาพ: item_5.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-005', NULL, 'ฐานธง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_6.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-006', NULL, 'ธงชาติไทย', 'พัสดุปกครอง ๒', 'ผืน', 0, 'ภาพ: item_7.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-007', NULL, 'ธงรัชกาลที่ 9', 'พัสดุปกครอง ๒', 'ผืน', 0, 'ภาพ: item_8.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-008', NULL, 'ผ้าห่ม ทอ.', 'พัสดุปกครอง ๑', 'ผืน', 0, 'ภาพ: item_9.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-009', NULL, 'หมวกหม้อตาลขาว', 'พัสดุปกครอง ๑', 'ใบ', 0, 'ภาพ: item_10.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-010', NULL, 'หมวกหม้อตาล', 'พัสดุปกครอง ๑', 'ใบ', 0, 'ภาพ: item_11.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-011', NULL, 'สายคาดหมวกสีทอง', 'พัสดุปกครอง ๑', 'เส้น', 0, 'ภาพ: item_12.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-012', NULL, 'โต๊ะหมู่', 'พัสดุปกครอง ๒', 'ตัว', 0, 'ภาพ: item_13.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-013', NULL, 'เก้าอี้ไม้เล็ก', 'พัสดุปกครอง ๒', 'ตัว', 0, 'ภาพ: item_14.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-014', NULL, 'ผ้าพันคอสามเหลี่ยม ส้ม', 'พัสดุปกครอง ๑', 'ผืน', 0, 'ภาพ: item_15.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-015', NULL, 'ผ้าพันคอสามเหลี่ยม ชมพู', 'พัสดุปกครอง ๑', 'ผืน', 0, 'ภาพ: item_16.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-016', NULL, 'ผ้าสีเหลี่ยมผืนผ้า น้ำเงิน', 'พัสดุปกครอง ๓', 'ผืน', 0, 'ภาพ: item_17.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-017', NULL, 'ผ้าสีเหลี่ยมผืนผ้า เหลือง', 'พัสดุปกครอง ๓', 'ผืน', 0, 'ภาพ: item_18.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-018', NULL, 'ลูกปิงปอง', 'พัสดุปกครอง ๓', 'ชุด', 0, 'ภาพ: item_19.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-019', NULL, 'พานพุ่ม ทอง', 'พัสดุปกครอง ๒', 'พุ่ม', 0, 'ภาพ: item_20.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-020', NULL, 'พานพุ่ม เงิน', 'พัสดุปกครอง ๒', 'พุ่ม', 0, 'ภาพ: item_21.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-021', NULL, 'ผ้าปิดตา', 'พัสดุปกครอง ๑', 'ผืน', 0, 'ภาพ: item_22.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-022', NULL, 'ลูกแก้ว', 'พัสดุปกครอง ๓', 'ชุด', 0, 'ภาพ: item_23.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-023', NULL, 'เสื้อปฏิบัติธรรม size S', 'พัสดุปกครอง ๑', 'ตัว', 0, 'ภาพ: item_24.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-024', NULL, 'เสื้อปฏิบัติธรรม size M', 'พัสดุปกครอง ๑', 'ตัว', 0, 'ภาพ: item_25.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-025', NULL, 'เสื้อปฏิบัติธรรม size 2', 'พัสดุปกครอง ๑', 'ตัว', 0, 'ภาพ: item_26.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-026', NULL, 'เสื้อปฏิบัติธรรม ไม่มี size', 'พัสดุปกครอง ๑', 'ตัว', 0, 'ภาพ: item_27.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-027', NULL, 'ตะเกียบ', 'พัสดุปกครอง ๓', 'ชุด', 0, 'ภาพ: item_28.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-028', NULL, 'ลูกเทนนิส', 'พัสดุปกครอง ๓', 'ชุด', 0, 'ภาพ: item_29.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-029', NULL, 'ผ้าพันคอสามเหลี่ยม เหลือง', 'พัสดุปกครอง ๑', 'ผืน', 0, 'ภาพ: item_30.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-030', NULL, 'ผ้าพันคอสามเหลี่ยม ฟ้า', 'พัสดุปกครอง ๑', 'ผืน', 0, 'ภาพ: item_31.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-031', NULL, 'ผ้าพันคอสามเหลี่ยม แดง', 'พัสดุปกครอง ๑', 'ผืน', 0, 'ภาพ: item_32.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-032', NULL, 'ผ้าพันคอสามเหลี่ยม เขียว', 'พัสดุปกครอง ๑', 'ผืน', 0, 'ภาพ: item_33.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-033', NULL, 'แว่นตาว่ายน้ำ', 'พัสดุปกครอง ๑', 'ชิ้น', 0, 'ภาพ: item_34.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-034', NULL, 'กางเกงปฏิบัติธรรม size M', 'พัสดุปกครอง ๑', 'ตัว', 0, 'ภาพ: item_35.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-035', NULL, 'กางเกงปฏิบัติธรรม size L', 'พัสดุปกครอง ๑', 'ตัว', 0, 'ภาพ: item_36.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-036', NULL, 'เชือง แดง', 'พัสดุปกครอง ๓', 'เส้น', 0, 'ภาพ: item_37.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-037', NULL, 'เชือง ขาว', 'พัสดุปกครอง ๓', 'เส้น', 0, 'ภาพ: item_38.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-038', NULL, 'คูเลอร์', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_39.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-039', NULL, 'ผ้าถุง', 'พัสดุปกครอง ๑', 'ผืน', 0, 'ภาพ: item_40.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-040', NULL, 'ผ้าคาดบ่า', 'พัสดุปกครอง ๑', 'ผืน', 0, 'ภาพ: item_41.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-041', NULL, 'ถังฆ้าเชื้อ', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_42.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-042', NULL, 'ผ้าคลุมเต้น', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_43.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-043', NULL, 'เสาเตนท์', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_44.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-044', NULL, 'ชุดดับเพลิง', 'พัสดุปกครอง ๓', 'ชุด', 0, 'ภาพ: item_45.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-045', NULL, 'ถุงมือผ้า', 'พัสดุปกครอง ๑', 'คู่', 0, 'ภาพ: item_46.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-046', NULL, 'รองเท้าคอมแบท size 37', 'พัสดุปกครอง ๑', 'คู่', 0, 'ภาพ: item_47.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-047', NULL, 'รองเท้าคอมแบท size 38', 'พัสดุปกครอง ๑', 'คู่', 0, 'ภาพ: item_48.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-048', NULL, 'รองเท้าคอมแบท size 39', 'พัสดุปกครอง ๑', 'คู่', 0, 'ภาพ: item_49.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-049', NULL, 'รองเท้าคอมแบท size 40', 'พัสดุปกครอง ๑', 'คู่', 0, 'ภาพ: item_50.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-050', NULL, 'เป้สนาม', 'พัสดุปกครอง ๑', 'ใบ', 0, 'ภาพ: item_51.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-051', NULL, 'ฟ้อกกี้', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_52.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-052', NULL, 'ธงตราวพอ.พอ. เหลือง', 'พัสดุปกครอง ๒', 'ชิ้น', 0, 'ภาพ: item_53.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-053', NULL, 'ธงตราวพอ.พอ. ชมพู', 'พัสดุปกครอง ๒', 'ชิ้น', 0, 'ภาพ: item_54.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-054', NULL, 'ธงตราวพอ.พอ. เขียว', 'พัสดุปกครอง ๒', 'ชิ้น', 0, 'ภาพ: item_55.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-055', NULL, 'ธงตราวพอ.พอ. ส้ม', 'พัสดุปกครอง ๒', 'ชิ้น', 0, 'ภาพ: item_56.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-056', NULL, 'กระติกน้ำ เหลี่ยม', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_57.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-057', NULL, 'กระติกน้ำ กลม', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_58.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-058', NULL, 'ถาดเงิน ใหญ่', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_59.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-059', NULL, 'ถาดเงิน กลาง', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_60.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-060', NULL, 'ถาดเงิน เล็ก', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_61.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-061', NULL, 'พานทอง ใหญ่', 'พัสดุปกครอง ๒', 'ชิ้น', 0, 'ภาพ: item_62.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-062', NULL, 'ผ้าส้มลูกไม้ทอง', 'พัสดุปกครอง ๒', 'ผืน', 0, 'ภาพ: item_63.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-063', NULL, 'ผ้าส้มลูกไม้ขาว', 'พัสดุปกครอง ๒', 'ผืน', 0, 'ภาพ: item_64.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-064', NULL, 'ผ้าลูกไม้พระ', 'พัสดุปกครอง ๒', 'ผืน', 0, 'ภาพ: item_65.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-065', NULL, 'ชุดเทียน', 'พัสดุปกครอง ๒', 'ชุด', 0, 'ภาพ: item_66.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-066', NULL, 'เทียน', 'พัสดุปกครอง ๒', 'เล่ม', 0, 'ภาพ: item_67.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-067', NULL, 'สายสิญจน์', 'พัสดุปกครอง ๒', 'ม้วน', 0, 'ภาพ: item_68.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-068', NULL, 'เทียน เทา', 'พัสดุปกครอง ๒', 'แพ็ค', 0, 'ภาพ: item_69.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-069', NULL, 'เทียน ชมพู', 'พัสดุปกครอง ๒', 'แพ็ค', 0, 'ภาพ: item_70.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-070', NULL, 'เทียน เหลือง', 'พัสดุปกครอง ๒', 'แพ็ค', 0, 'ภาพ: item_71.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-071', NULL, 'เทียน เหลือง', 'พัสดุปกครอง ๒', 'แพ็ค', 0, 'ภาพ: item_72.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-072', NULL, 'เสาธง ขาว', 'พัสดุปกครอง ๒', 'ไม้', 0, 'ภาพ: item_73.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-073', NULL, 'เสาธง หัวไม้', 'พัสดุปกครอง ๒', 'ไม้', 0, 'ภาพ: item_74.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-074', NULL, 'เสาธง หัวชุบ', 'พัสดุปกครอง ๒', 'ไม้', 0, 'ภาพ: item_75.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-075', NULL, 'เสาธง หัวชุบ', 'พัสดุปกครอง ๒', 'ไม้', 0, 'ภาพ: item_76.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-076', NULL, 'เสาธง หัวทู่่', 'พัสดุปกครอง ๒', 'ไม้', 0, 'ภาพ: item_77.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-077', NULL, 'เสาธง ขาว', 'พัสดุปกครอง ๒', 'ไม้', 0, 'ภาพ: item_78.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-078', NULL, 'เหล็กฐานแบน', 'พัสดุปกครอง ๒', 'เสา', 0, 'ภาพ: item_79.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-079', NULL, 'ป้าย วพอ.พอ.', 'พัสดุปกครอง ๒', 'ป้าย', 0, 'ภาพ: item_80.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-080', NULL, 'หม้อ ใหญ่', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_81.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-081', NULL, 'กล่องเก็บอปุกรณ์วิ่งแอโรบิค', 'พัสดุปกครอง ๓', 'กล่อง', 0, 'ภาพ: item_82.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-082', NULL, 'กล่องอุปกรณ์ กีฬาฮาเฮ', 'พัสดุปกครอง ๓', 'กล่อง', 0, 'ภาพ: item_83.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-083', NULL, 'ผ้าลอยกว่าคิด', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_84.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-084', NULL, 'หมอน', 'พัสดุปกครอง ๑', 'ใบ', 0, 'ภาพ: item_85.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-085', NULL, 'กล่องเปล่า', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_86.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-086', NULL, 'แก้วคอกเทล spy', 'พัสดุปกครอง ๓', 'กล่อง', 0, 'ภาพ: item_87.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-087', NULL, 'ชุดอุปกรณ์ผ้า', 'พัสดุปกครอง ๓', 'กล่อง', 0, 'ภาพ: item_88.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-APP-088', NULL, 'เสื้อเก่าบริจาค', 'พัสดุปกครอง ๑', 'ชุด', 0, 'ภาพ: item_89.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-089', NULL, 'พัด', 'พัสดุปกครอง ๓', 'ชิ้น', 0, 'ภาพ: item_90.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-090', NULL, 'ผ้าสไบไปวัด', 'พัสดุปกครอง ๒', 'กล่อง', 0, 'ภาพ: item_91.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-091', NULL, 'ถาดทอง', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_92.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-092', NULL, 'แก้วน้ำพระ', 'พัสดุปกครอง ๒', 'ชุด', 0, 'ภาพ: item_93.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-093', NULL, 'ถ้วยกาแฟสีขาว', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_94.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-094', NULL, 'แก้วน้ำ', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_95.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-095', NULL, 'หม้อสแตนเลส', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_96.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-096', NULL, 'ถาดสี่เหลี่ยมสแตนเลส', 'พัสดุปกครอง ๓', 'ชุด', 0, 'ภาพ: item_97.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-097', NULL, 'ถาดพลาสติกเขียว', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_98.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-098', NULL, 'กระบวย', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_99.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-099', NULL, 'จานใบไม้', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_100.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-100', NULL, 'จานขาวมน', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_101.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-101', NULL, 'ช้อนแพ็ค', 'พัสดุปกครอง ๓', 'แพ็ค 3คัน', 0, 'ภาพ: item_102.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-102', NULL, 'ส้อมแพ็ค', 'พัสดุปกครอง ๓', 'แพ็ค 5 คัน', 0, 'ภาพ: item_103.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-103', NULL, 'ชามสี่เหลี่ยม', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_104.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-104', NULL, 'แก้วกระดาษ', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_105.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-105', NULL, 'ที่ตักน้ำแข็ง', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_106.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-106', NULL, 'ชุดถ้วยฝาและช้อน', 'พัสดุปกครอง ๓', 'ชุด', 0, 'ภาพ: item_107.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-107', NULL, 'ที่คีบน้ำแข็ง', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_108.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-108', NULL, 'หลอดงอ ห่อฟิล์ม', 'พัสดุปกครอง ๓', 'เส้น', 0, 'ภาพ: item_109.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-109', NULL, 'กระติกน้ำแข็ง', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_110.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-110', NULL, 'ช้อนซุป', 'พัสดุปกครอง ๓', 'คัน', 0, 'ภาพ: item_111.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-111', NULL, 'ถ้วย', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_112.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-112', NULL, 'แก้วกาแฟ', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_113.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-113', NULL, 'จานรองแก้วใบใหญ่', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_114.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-114', NULL, 'จานรองแก้วใบเล็ก', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_115.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-115', NULL, 'จานใบไม้', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_116.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-116', NULL, 'จานใบไม้', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_117.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-117', NULL, 'ชามใบใหญ่', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_118.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-118', NULL, 'ชามใบเล็ก', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_119.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-119', NULL, 'ถาดสี่เหลี่ยมขาว', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_120.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-120', NULL, 'แก้วไวน์ทรงเตี้ย', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_121.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-121', NULL, 'แก้วน้ำ', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_122.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-122', NULL, 'จานรอง', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_123.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-123', NULL, 'ชุดถ้วยช้อน', 'พัสดุปกครอง ๓', 'ชุด', 0, 'ภาพ: item_124.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-124', NULL, 'เสลี่ยง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_125.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-125', NULL, 'ชามแก้ว', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_126.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-126', NULL, 'พานพุ่มสีทอง ขนาดกลาง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_127.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-127', NULL, 'โถแสตนเลต', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_128.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-128', NULL, 'กระโถนใหญ่', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_129.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-129', NULL, 'พานโตกสีเงินขนาดกลาง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_130.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-130', NULL, 'กระโถนเล็ก', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_131.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-131', NULL, 'พานโตกสีทองขนาดกลาง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_132.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-132', NULL, 'พานโตกสีทองขนาดใหญ่', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_133.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-133', NULL, 'ถาดเงิน', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_134.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-134', NULL, 'พานบัวหลวงสีเงินขนาดกลาง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_135.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-135', NULL, 'เชิงเทียนทอง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_136.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-136', NULL, 'ที่กรวดน้ำสีทอง', 'พัสดุปกครอง ๒', 'ชุด', 0, 'ภาพ: item_137.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-137', NULL, 'พานอะลูมิเนียมสีทองขนาดเล็ก', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_138.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-138', NULL, 'กาน้ำร้อน', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_139.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-139', NULL, 'พานโตกสีทองขนาดเล็ก', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_140.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-140', NULL, 'กล่องหย่อนฉลาก', 'พัสดุปกครอง ๓', 'กล่อง', 0, 'ภาพ: item_141.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-141', NULL, 'พานกลมสีทอง ขนาดกลาง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_142.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-142', NULL, 'ขันเงิน.ขนาดใหญ่', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_143.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-143', NULL, 'พานขันโตกสีเงินขนาดใหญ่', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_144.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-144', NULL, 'ขันเงินขนาดเบอร์ 2', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_145.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-145', NULL, 'ขันเงินขนาดเบอร์ 3', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_146.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-146', NULL, 'ขันเงินขนาดเบอร์ 4', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_147.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-147', NULL, 'ขันเงินขนาดเบอร์ 5', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_148.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-148', NULL, 'ขันเงินเบอร์ 6', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_149.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-149', NULL, 'ขันเงินเบอร์ 7', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_150.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-150', NULL, 'ขันทองเบอร์ 8', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_151.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-151', NULL, 'ขันเงินเบอร์ 9', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_152.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-152', NULL, 'ขันเงินเบอร์ 10', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_153.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-153', NULL, 'ขันเงินเบอร์ 8', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_154.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-154', NULL, 'ขันเงินเบอร์ 11', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_155.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-155', NULL, 'แก้วสีแดง', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_156.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-156', NULL, 'แก้้วสีเขียว', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_157.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-157', NULL, 'แก้วทรงดอกไม้', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_158.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-158', NULL, 'พานกลมสีทอง ขนาดกลาง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_159.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-159', NULL, 'แก้ว', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_160.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-160', NULL, 'ถาดข้าวสีแดง', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_161.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-161', NULL, 'ถ้วยเซรามิก', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_162.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-162', NULL, 'แก้วพลาสติก', 'พัสดุปกครอง ๓', 'อัน', 0, 'ภาพ: item_163.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-163', NULL, 'แก้ว', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_164.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-164', NULL, 'พานขนาดเล็ก', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_165.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-165', NULL, 'ถาดข้าวสีขาว', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_166.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-OPS-166', NULL, 'ถาดข้าวสีฟ้า', 'พัสดุปกครอง ๓', 'ใบ', 0, 'ภาพ: item_167.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-167', NULL, 'พานขนาดกลาง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_168.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-168', NULL, 'พานขนาดใหญ่', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_169.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-169', NULL, 'พานขันโตกสีเงินขนาดกลาง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_170.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-170', NULL, 'แท่นไม้', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_171.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-171', NULL, 'กาน้ำชา', 'พัสดุปกครอง ๒', 'ชุด', 0, 'ภาพ: item_172.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-172', NULL, 'กระถางธูป', 'พัสดุปกครอง ๒', 'ชุด', 0, 'ภาพ: item_173.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-173', NULL, 'พานโตกสีเงินขนาดกลาง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_174.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-174', NULL, 'พานแก้วขนาดเล็ก', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_175.jpg | สถานะ: พร้อมใช้งาน', 1),
('GOV-CER-175', NULL, 'พานแก้วขนาดกลาง', 'พัสดุปกครอง ๒', 'อัน', 0, 'ภาพ: item_176.jpg | สถานะ: พร้อมใช้งาน', 1);

INSERT INTO stock_levels (product_id, location_id, qty) VALUES
((SELECT id FROM products WHERE sku='GOV-APP-001'), (SELECT id FROM locations WHERE code='GOV-WH'), 12),
((SELECT id FROM products WHERE sku='GOV-APP-002'), (SELECT id FROM locations WHERE code='GOV-WH'), 20),
((SELECT id FROM products WHERE sku='GOV-APP-003'), (SELECT id FROM locations WHERE code='GOV-WH'), 40),
((SELECT id FROM products WHERE sku='GOV-APP-004'), (SELECT id FROM locations WHERE code='GOV-WH'), 43),
((SELECT id FROM products WHERE sku='GOV-CER-005'), (SELECT id FROM locations WHERE code='GOV-WH'), 4),
((SELECT id FROM products WHERE sku='GOV-CER-006'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-CER-007'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-APP-008'), (SELECT id FROM locations WHERE code='GOV-WH'), 7),
((SELECT id FROM products WHERE sku='GOV-APP-009'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-APP-010'), (SELECT id FROM locations WHERE code='GOV-WH'), 12),
((SELECT id FROM products WHERE sku='GOV-APP-011'), (SELECT id FROM locations WHERE code='GOV-WH'), 42),
((SELECT id FROM products WHERE sku='GOV-CER-012'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-CER-013'), (SELECT id FROM locations WHERE code='GOV-WH'), 5),
((SELECT id FROM products WHERE sku='GOV-APP-014'), (SELECT id FROM locations WHERE code='GOV-WH'), 35),
((SELECT id FROM products WHERE sku='GOV-APP-015'), (SELECT id FROM locations WHERE code='GOV-WH'), 23),
((SELECT id FROM products WHERE sku='GOV-OPS-016'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-017'), (SELECT id FROM locations WHERE code='GOV-WH'), 4),
((SELECT id FROM products WHERE sku='GOV-OPS-018'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-019'), (SELECT id FROM locations WHERE code='GOV-WH'), 3),
((SELECT id FROM products WHERE sku='GOV-CER-020'), (SELECT id FROM locations WHERE code='GOV-WH'), 3),
((SELECT id FROM products WHERE sku='GOV-APP-021'), (SELECT id FROM locations WHERE code='GOV-WH'), 14),
((SELECT id FROM products WHERE sku='GOV-OPS-022'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-APP-023'), (SELECT id FROM locations WHERE code='GOV-WH'), 4),
((SELECT id FROM products WHERE sku='GOV-APP-024'), (SELECT id FROM locations WHERE code='GOV-WH'), 9),
((SELECT id FROM products WHERE sku='GOV-APP-025'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-APP-026'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-027'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-028'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-APP-029'), (SELECT id FROM locations WHERE code='GOV-WH'), 15),
((SELECT id FROM products WHERE sku='GOV-APP-030'), (SELECT id FROM locations WHERE code='GOV-WH'), 18),
((SELECT id FROM products WHERE sku='GOV-APP-031'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-APP-032'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-APP-033'), (SELECT id FROM locations WHERE code='GOV-WH'), 16),
((SELECT id FROM products WHERE sku='GOV-APP-034'), (SELECT id FROM locations WHERE code='GOV-WH'), 66),
((SELECT id FROM products WHERE sku='GOV-APP-035'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-036'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-037'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-038'), (SELECT id FROM locations WHERE code='GOV-WH'), 9),
((SELECT id FROM products WHERE sku='GOV-APP-039'), (SELECT id FROM locations WHERE code='GOV-WH'), 107),
((SELECT id FROM products WHERE sku='GOV-APP-040'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-041'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-042'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-OPS-043'), (SELECT id FROM locations WHERE code='GOV-WH'), 14),
((SELECT id FROM products WHERE sku='GOV-OPS-044'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-APP-045'), (SELECT id FROM locations WHERE code='GOV-WH'), 13),
((SELECT id FROM products WHERE sku='GOV-APP-046'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-APP-047'), (SELECT id FROM locations WHERE code='GOV-WH'), 8),
((SELECT id FROM products WHERE sku='GOV-APP-048'), (SELECT id FROM locations WHERE code='GOV-WH'), 10),
((SELECT id FROM products WHERE sku='GOV-APP-049'), (SELECT id FROM locations WHERE code='GOV-WH'), 13),
((SELECT id FROM products WHERE sku='GOV-APP-050'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-051'), (SELECT id FROM locations WHERE code='GOV-WH'), 3),
((SELECT id FROM products WHERE sku='GOV-CER-052'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-053'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-054'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-055'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-056'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-057'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-058'), (SELECT id FROM locations WHERE code='GOV-WH'), 4),
((SELECT id FROM products WHERE sku='GOV-OPS-059'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-060'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-061'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-062'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-063'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-064'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-065'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-066'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-067'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-068'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-CER-069'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-070'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-071'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-072'), (SELECT id FROM locations WHERE code='GOV-WH'), 10),
((SELECT id FROM products WHERE sku='GOV-CER-073'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-074'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-075'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-076'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-077'), (SELECT id FROM locations WHERE code='GOV-WH'), 15),
((SELECT id FROM products WHERE sku='GOV-CER-078'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-079'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-080'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-081'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-082'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-083'), (SELECT id FROM locations WHERE code='GOV-WH'), 3),
((SELECT id FROM products WHERE sku='GOV-APP-084'), (SELECT id FROM locations WHERE code='GOV-WH'), 40),
((SELECT id FROM products WHERE sku='GOV-OPS-085'), (SELECT id FROM locations WHERE code='GOV-WH'), 4),
((SELECT id FROM products WHERE sku='GOV-OPS-086'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-087'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-APP-088'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-089'), (SELECT id FROM locations WHERE code='GOV-WH'), 17),
((SELECT id FROM products WHERE sku='GOV-CER-090'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-091'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-092'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-093'), (SELECT id FROM locations WHERE code='GOV-WH'), 9),
((SELECT id FROM products WHERE sku='GOV-OPS-094'), (SELECT id FROM locations WHERE code='GOV-WH'), 92),
((SELECT id FROM products WHERE sku='GOV-OPS-095'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-096'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-097'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-098'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-099'), (SELECT id FROM locations WHERE code='GOV-WH'), 5),
((SELECT id FROM products WHERE sku='GOV-OPS-100'), (SELECT id FROM locations WHERE code='GOV-WH'), 7),
((SELECT id FROM products WHERE sku='GOV-OPS-101'), (SELECT id FROM locations WHERE code='GOV-WH'), 4),
((SELECT id FROM products WHERE sku='GOV-OPS-102'), (SELECT id FROM locations WHERE code='GOV-WH'), 7),
((SELECT id FROM products WHERE sku='GOV-OPS-103'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-104'), (SELECT id FROM locations WHERE code='GOV-WH'), 200),
((SELECT id FROM products WHERE sku='GOV-OPS-105'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-106'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-107'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-108'), (SELECT id FROM locations WHERE code='GOV-WH'), 200),
((SELECT id FROM products WHERE sku='GOV-OPS-109'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-110'), (SELECT id FROM locations WHERE code='GOV-WH'), 9),
((SELECT id FROM products WHERE sku='GOV-OPS-111'), (SELECT id FROM locations WHERE code='GOV-WH'), 8),
((SELECT id FROM products WHERE sku='GOV-OPS-112'), (SELECT id FROM locations WHERE code='GOV-WH'), 4),
((SELECT id FROM products WHERE sku='GOV-OPS-113'), (SELECT id FROM locations WHERE code='GOV-WH'), 3),
((SELECT id FROM products WHERE sku='GOV-OPS-114'), (SELECT id FROM locations WHERE code='GOV-WH'), 16),
((SELECT id FROM products WHERE sku='GOV-OPS-115'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-116'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-117'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-118'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-119'), (SELECT id FROM locations WHERE code='GOV-WH'), 11),
((SELECT id FROM products WHERE sku='GOV-OPS-120'), (SELECT id FROM locations WHERE code='GOV-WH'), 22),
((SELECT id FROM products WHERE sku='GOV-OPS-121'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-OPS-122'), (SELECT id FROM locations WHERE code='GOV-WH'), 5),
((SELECT id FROM products WHERE sku='GOV-OPS-123'), (SELECT id FROM locations WHERE code='GOV-WH'), 10),
((SELECT id FROM products WHERE sku='GOV-CER-124'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-125'), (SELECT id FROM locations WHERE code='GOV-WH'), 7),
((SELECT id FROM products WHERE sku='GOV-CER-126'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-127'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-128'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-129'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-130'), (SELECT id FROM locations WHERE code='GOV-WH'), 3),
((SELECT id FROM products WHERE sku='GOV-CER-131'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-132'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-133'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-134'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-135'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-136'), (SELECT id FROM locations WHERE code='GOV-WH'), 3),
((SELECT id FROM products WHERE sku='GOV-CER-137'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-138'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-139'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-OPS-140'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-CER-141'), (SELECT id FROM locations WHERE code='GOV-WH'), 5),
((SELECT id FROM products WHERE sku='GOV-CER-142'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-143'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-144'), (SELECT id FROM locations WHERE code='GOV-WH'), 3),
((SELECT id FROM products WHERE sku='GOV-CER-145'), (SELECT id FROM locations WHERE code='GOV-WH'), 15),
((SELECT id FROM products WHERE sku='GOV-CER-146'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-147'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-148'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-CER-149'), (SELECT id FROM locations WHERE code='GOV-WH'), 18),
((SELECT id FROM products WHERE sku='GOV-CER-150'), (SELECT id FROM locations WHERE code='GOV-WH'), 10),
((SELECT id FROM products WHERE sku='GOV-CER-151'), (SELECT id FROM locations WHERE code='GOV-WH'), 13),
((SELECT id FROM products WHERE sku='GOV-CER-152'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-CER-153'), (SELECT id FROM locations WHERE code='GOV-WH'), 4),
((SELECT id FROM products WHERE sku='GOV-CER-154'), (SELECT id FROM locations WHERE code='GOV-WH'), 4),
((SELECT id FROM products WHERE sku='GOV-OPS-155'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-OPS-156'), (SELECT id FROM locations WHERE code='GOV-WH'), 6),
((SELECT id FROM products WHERE sku='GOV-OPS-157'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-158'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-159'), (SELECT id FROM locations WHERE code='GOV-WH'), 50),
((SELECT id FROM products WHERE sku='GOV-OPS-160'), (SELECT id FROM locations WHERE code='GOV-WH'), 101),
((SELECT id FROM products WHERE sku='GOV-OPS-161'), (SELECT id FROM locations WHERE code='GOV-WH'), 3),
((SELECT id FROM products WHERE sku='GOV-OPS-162'), (SELECT id FROM locations WHERE code='GOV-WH'), 103),
((SELECT id FROM products WHERE sku='GOV-OPS-163'), (SELECT id FROM locations WHERE code='GOV-WH'), 3),
((SELECT id FROM products WHERE sku='GOV-CER-164'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-OPS-165'), (SELECT id FROM locations WHERE code='GOV-WH'), 25),
((SELECT id FROM products WHERE sku='GOV-OPS-166'), (SELECT id FROM locations WHERE code='GOV-WH'), 65),
((SELECT id FROM products WHERE sku='GOV-CER-167'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-168'), (SELECT id FROM locations WHERE code='GOV-WH'), 2),
((SELECT id FROM products WHERE sku='GOV-CER-169'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-170'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-171'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-172'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-173'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-174'), (SELECT id FROM locations WHERE code='GOV-WH'), 1),
((SELECT id FROM products WHERE sku='GOV-CER-175'), (SELECT id FROM locations WHERE code='GOV-WH'), 1);
